In [ ]:
# anaconda 설치
#conda install pytorch torchvision torchaudio -c pytorch


# 1. Tensor
* PyTorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)합니다.
*  NumPy 의 ndarray와 유사
* 자동 미분(automatic differentiation)에 최적화


In [ ]:
import torch
import numpy as np

In [ ]:
# 1. Tensor 초기화 =====================================================================================

#데이터로 부터 직접(directly) 초기화
# --> 데이터 자료형은 자동으로 유추합니다.

data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
#numpy 배열로 부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
#텐서 속성 --> override 하지 않으면, 그대로 유지

x_ones = torch.ones_like(x_data) # -> x_data 속성을 유지
print(f'Ones Tensor:\n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype=torch.float) # -> x_data 속성을 뒤집어씀
print(f'Rand Tensor:\n {x_rand} \n')

Ones Tensor:
 tensor([[1, 1],
        [1, 1]]) 

Rand Tensor:
 tensor([[0.5492, 0.3294],
        [0.1230, 0.3479]]) 



In [ ]:
#random or constant 값 사용하기
shape = (2,3,)  # -> tensor 의 속성을 나타내는 tuple
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7903, 0.4238, 0.6748],
        [0.7263, 0.9806, 0.0449]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [ ]:
# 2. tensor의 Attribute =====================================================================================

tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# 3. tensor 연산 =====================================================================================

# 기본적으로 텐서는 CPU에 생성됩니다. 
# .to 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있습니다. 
# 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다는 것을 기억하세요!


# GPU 가 존재하면 텐서를 이동합니다.
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

# 표준 인덱싱과 슬라이싱
tensor = torch.ones(4,4)
print('First row: \n', tensor[0])
print('\n First column: \n', tensor[:, 0])
print('\n Last column: \n', tensor[..., -1])
tensor[:,1] = 0
print('\n', tensor)
print('\n', tensor.device) # colab에서는 런타임을 통해 기기 변경

First row: 
 tensor([1., 1., 1., 1.])

 First column: 
 tensor([1., 1., 1., 1.])

 Last column: 
 tensor([1., 1., 1., 1.])

 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

 cpu


<h3> cat

In [ ]:
# 주어진 차원에 따라 일련의 텐서 연결
# -- torch.cat 과 미묘하게 다른 또 다른 텐서 결합 연산인 torch.stack 도 참고해보세요.
print(f'torch is \n {tensor} \n')
t1 = torch.cat([tensor, tensor, tensor], dim=1) # -> 열 증가, dim=0은 행 증가
print(t1)

torch is 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


<h3> stack

In [ ]:
t2 = torch.stack([tensor, tensor, tensor], dim=1) # -> y축으로 tensor 2개를 더 stack / tensor를 (x,z)로 본다
print(t2)
print(' \n =============================== \n')
t3 = torch.stack([tensor, tensor, tensor], dim=0) # -> z축으로 tensor 2개를 더 stack / tensor를 (x,y)로 본다
print(t3)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


<h3> 산술연산(Arithmetic operations)

In [ ]:
#산술 연산(Arithmetic operations)

# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
print(y1, '\n')

y2 = tensor.matmul(tensor.T)
print(y2, '\n')

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out = y3)
print(y3, '\n')



tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



In [ ]:
# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
print(tensor, '\n')

z1 = tensor * tensor
print('\n', z1)

z2 = tensor.mul(tensor)
print('\n', z2)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print('\n', z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 


 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# 단일-요소(single-element) 텐서의 모든 값을 하나로 집계(aggregate)하여
# 요소가 하나인 텐서의 경우, item() 을 사용하여 Python 숫자 값으로 변환할 수 있습니다.

agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
# 바꿔치기(in-place) 연산 : 연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, _ 접미사를 갖습니다. 
# 예를 들어: x.copy_(y) 나 x.t_() 는 x 를 변경합니다.

print(tensor, "\n")
tensor.add_(5)
print(tensor)

# 바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다. 따라서, 사용을 권장하지 않습니다.

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<h3> Numpy 변환 (Bridge)

* CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, **하나를 변경하면 다른 하나도 변경됩니다.** ⭐


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

In [ ]:
# 텐서 -> numpy
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
# 텐서를 변경하면, numpy도 변경된다!
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
# numpy -> 텐서
n = np.ones(5)
t = torch.from_numpy(n)
print('t: ', t)

t:  tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
# NumPy 배열의 변경 사항이 텐서에 반영!
np.add(n, 1, out=n)
print(f't: {t}')
print(f'n: {n}')

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]
